version: "3.7"

x-container: &base-config
  build:
    context: ./
    dockerfile: docker/Dockerfile.dev
    args:
        - USER_NAME=${USER_NAME}
        - GROUP_NAME=${GROUP_NAME}
        - UID=${UID}
        - GID=${GID}
  image: vue-ros-interface:dev
  user: "${UID}:${GID}"
  tty: true
  env_file:
      - .env

volumes:
  robot.db.volume:
    name: robot.db.volume

services:
  nginx:
    image: nginx
    container_name: robot.nginx
    ports:
        - "8000:8000"
    volumes:
        - ./nginx/robot_nginx.conf:/etc/nginx/conf.d/robot_nginx.conf
        - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
    depends_on:
        - backend

  db:
    image: postgres:15.4
    container_name: robot.db
    ports:
        - "5433:5432"
    env_file:
        - .env
    volumes:
        - robot.db.volume:/var/lib/postgresql/data

  backend:
    <<: *base-config
    container_name: robot.backend.dev
    expose:
        - "8080"
    volumes:
        - ./backend:/app
        - ./uwsgi:/etc/uwsgi
    depends_on:
        - db

  frontend:
    <<: *base-config
    container_name: robot.frontend.dev
    ports:
        - "3000:3000"
    volumes:
        - ./frontend:/app

