version: "3.7"

x-container: &base-config
  build:
    context: ./
    dockerfile: docker/Dockerfile
    args:
        - USER_NAME=${USER_NAME}
        - GROUP_NAME=${GROUP_NAME}
        - UID=${UID}
        - GID=${GID}
  image: vue-ros-interface:latest
  user: "${UID}:${GID}"
  tty: true
  env_file:
      - .env

volumes:
  robot_db:
    driver_opts:
      type: none
      device: ./postgres/robot_db
      o: bind

networks:
  robot_net:
    driver: bridge

services:
  nginx:
    image: nginx
    container_name: robot.nginx
    ports:
        - "8000:8000"
    volumes:
        - ./nginx/robot_nginx.conf:/etc/nginx/conf.d/robot_nginx.conf
        - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
        - ./nginx/log:/var/log/nginx
    networks:
        - robot_net
    depends_on:
        - backend

  db:
    image: postgres:15.4
    container_name: robot.db
    ports:
        - "5433:5432"
    env_file:
        - .env
    volumes:
        - ./postgres/robot_db:/var/lib/postgresql/data
    hostname: postgres
    networks:
        - robot_net

  backend:
    <<: *base-config
    container_name: robot.backend
    expose:
        - "8080"
    volumes:
        - ./backend:/app
        - ./uwsgi:/uwsgi
    command: ["uwsgi", "--ini", "/uwsgi/uwsgi.ini"]
    networks:
        - robot_net
    depends_on:
        - db

  frontend:
    <<: *base-config
    container_name: robot.frontend
    ports:
        - "3000:3000"
    volumes:
        - ./frontend:/app
    command: ["/bin/bash", "-c", "npm run --prefix robot_ui serve -- --port 3000"]
    networks:
        - robot_net

