version: "3.7"

services:
  nginx:
    image: nginx
    container_name: robot.nginx
    ports:
        - "8000:8000"
    volumes:
        - ./nginx/conf:/etc/nginx/conf.d
        - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
    depends_on:
        - backend

  backend:
    build:
      context: ./
      dockerfile: docker/Dockerfile.backend
    container_name: robot.backend
    expose:
        - "8000"
    volumes:
        - ./backend:/app
        - ./uwsgi:/etc/uwsgi

