version: "3.7"

volumes:
  robot_db:
    driver_opts:
      type: none
      device: ./postgres/robot_db
      o: bind

x-container: &base-config
  build:
    context: ./
    dockerfile: docker/Dockerfile
    args:
        - USER_NAME=${USER_NAME}
        - GROUP_NAME=${GROUP_NAME}
        - UID=${UID}
        - GID=${GID}
  image: vue-ros-interface:latest
  user: "${UID}:${GID}"
  tty: true
  env_file:
      - .env

services:
  nginx:
    image: nginx
    container_name: robot.nginx
    ports:
        - "8000:80"
    network_mode: robot_net
    depends_on:
        - backend
    volumes:
        - ./nginx/robot_nginx.conf:/etc/nginx/conf.d/robot_nginx.conf
        - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
        - ./nginx/log:/var/log/nginx
        - ./backend/robot_site/static:/static
        - ./frontend/robot_ui:/frontend
    command: ["nginx", "-g", "daemon off;"]

  redis:
    image: redis:7
    container_name: robot.redis
    network_mode: robot_net
    expose:
        - 6379
    env_file:
        - .env

  db:
    image: postgres:15.4
    container_name: robot.db
    env_file:
        - .env
    hostname: postgres
    network_mode: robot_net
    expose:
        - 5432
    volumes:
        - ./postgres/robot_db:/var/lib/postgresql/data

  backend:
    <<: *base-config
    container_name: robot.backend
    network_mode: robot_net
    ports:
      - 8080:8080
    depends_on:
        - redis
        - db
    volumes:
        - ./backend/robot_site:/app
        # - ./backend/test_site/mysite:/app
    # command: ["daphne", "-p 8080", "robot_site.asgi:application"]
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8080"]
    # command: ["su", "-", "${USER_NAME}"]

  frontend:
    <<: *base-config
    container_name: robot.frontend
    network_mode: robot_net
    ports:
        - "3000:3000"
    depends_on:
        - backend
    volumes:
        - ./frontend/robot_ui:/app
        - ./backend/robot_site/static:/static
    command: ["/bin/bash", "-c", "npm run -s build"] # for build
    # command: ["/bin/bash", "-c", "npm run serve -- --port 3000"] # for developing

  rosbridge:
    build:
      context: ./
      dockerfile: docker/Dockerfile.rosbridge
      args:
          - USER_NAME=${USER_NAME}
          - GROUP_NAME=${GROUP_NAME}
          - UID=${UID}
          - GID=${GID}
    image: rosbridge:latest
    container_name: robot.bridge
    user: "${UID}:${GID}"
    network_mode: robot_net
    ports:
        - "9090:9090"
    tty: true
    env_file:
        - .env

